In [4]:
from sklearn import tree
from sklearn import svm
from sklearn import ensemble
from sklearn import neighbors
from sklearn import linear_model
from sklearn import metrics
from sklearn import preprocessing

In [5]:
%matplotlib inline

from IPython.display import Image
import matplotlib as mlp
import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd
import sklearn
import seaborn as sns

#fetching data into variables

In [6]:
df = pd.read_csv('https://raw.githubusercontent.com/dsrscientist/DSData/master/Telecom_customer_churn.csv')
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [7]:
print (df.shape)

(7043, 21)

In [9]:
y = df["churn"].value_counts()
#print (y)
sns.barplot(y.index, y.values)

NameError: name 'y' is not defined

In [10]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [12]:
df.shape

(7043, 21)

In [13]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [ ]:
y = df['churn'].as_matrix().astype(np.int)
y.size

In [14]:
df.head(3)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes

In [15]:
X = df.as_matrix().astype(np.float)

AttributeError: 'DataFrame' object has no attribute 'as_matrix'

In [16]:
X

NameError: name 'X' is not defined

In [ ]:
X.shape

In [ ]:
sacler= preprocessing.StandardScaler()
X = Scaler.fit_transform(X)

In [ ]:
X

In [ ]:
def stratified_cv(X, y, clf_class, shuffle=True, n_folds=10,):
    stratified_k_fold = cross_validation.StratifiedKFold(y, n_folds=n_folds, shuffle=shuffle)
    y_pred = y.copy()
    # ii-> train
    # jj->test indices
    for ii, jj in stratified_k_fold:
        x_train, x_test = X[ii], X[jj]
        y_train = y[ii]
        clf = clf_class
        clf.fit(X_train,y_train)
        y_pred[jj] = clf.predict(x_test)
    return y_pred

Confusion matrices for various models

In [ ]:
grad_ens_conf_matrix = metrics.confusion_matrix(y, stratified_cv(X, y, 
                                ensemble.GradientBoostingClassifier))
sns.heatmap(grad_ens_conf_matrix, annot=True, fmt='')
title = 'GradientBoosting'
pli.title(title);

In [ ]:
grad_ens_conf_matrix = metrics.confusion_matrix(y, stratified_cv(X, y, 
                                svm.SVC))
sns.heatmap(grad_ens_conf_matrix, annot=True, fmt='')
title = 'SVM'
pli.title(title);

In [ ]:
grad_ens_conf_matrix = metrics.confusion_matrix(y, stratified_cv(X, y, 
                                ensemble.RandomForestClassifier))
sns.heatmap(grad_ens_conf_matrix, annot=True, fmt='')
title = 'RandomForest'
pli.title(title);

In [ ]:
grad_ens_conf_matrix = metrics.confusion_matrix(y, stratified_cv(X, y, 
                                LogisticRegression))
sns.heatmap(grad_ens_conf_matrix, annot=True, fmt='')
title = 'LogisticRegression'
pli.title(title);

In [ ]:
gbc = ensemble.GradientBoostingClassifier()
gbc.fit(x,y)

In [17]:
#Get feature importance from the classifier
feature_importance = gbc.feature_importances_
print (gbc.feature_importances_)
feat_importances = pd.series(gbc.feature_importances_, index=df.columns)
feat_importances = feat_importances.nlargest(19)
feat_importances.plot(kind='barh', figsize=(10,10))

NameError: name 'gbc' is not defined